[book]
title = "Haxe Manual"
authors = ["Haxe Foundation"]
language = "en"
src = "content"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/HaxeFoundation/HaxeManual"
edit-url-template = "https://github.com/HaxeFoundation/HaxeManual/edit/master/{path}"

[output.html.search]
enable = true
